name: GitHub Actions Demo
run-name: ${{ github.actor }} is building html files
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: python3 src/scripts/generate_html.py 
