name: GitHub Actions Demo
run-name: ${{ github.actor }} python not working
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10' # install the python version needed

        - name: install python packages 
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        -name: run python script
        run: python src/scripts/generate_html.py
